### ISSUE TITLE
Support for empty files

### ISSUE THREAD

**Issue by se7en007** [j256/simplemagic#13]
An empty file will return null as well as when the file mime type is not found on running ContentInfoUtil#findMatch.

Is it be possible to add support for differentiating between two cases?

**Comment by se7en007** [comment]
This is also in analogous to the behaviour of *nux OSes file utility.

touch emptyFile
file emptyFile
emptyFile: empty

**Comment by j256** [comment]
Good idea.  Added to trunk.

**Comment by se7en007** [comment]
Thank you.
