### ISSUE TITLE
HTML detection fails with leading newline

### ISSUE THREAD

**Issue by Abdull** [j256/simplemagic#15]
Using version 1.8, simplemagic fails to recognize valid HTML input if the input starts with a newline:

```
@Test
public void testContentInfoUtil() {
    ContentInfoUtil ciu = new ContentInfoUtil();

    String someHtml = "<!doctype html><title>.</title>";
    ContentInfo someHtmlContentInfo = ciu.findMatch( someHtml.getBytes(StandardCharsets.UTF_8) );
    ContentType someHtmlContentType = someHtmlContentInfo.getContentType();
    assertTrue( ContentType.HTML.equals(someHtmlContentType) );
    // passes correctly

    String anotherHtml = "\n<!doctype html><title>.</title>"; // notice the leading newline
    ContentInfo anotherHtmlContentInfo = ciu.findMatch( anotherHtml.getBytes(StandardCharsets.UTF_8) );
    ContentType anotherHtmlContentType = anotherHtmlContentInfo.getContentType(); // java.lang.NullPointerException
    // from here onwards unreachable
    assertTrue( ContentType.HTML.equals(anotherHtmlContentType) );
}
```

According to https://validator.w3.org , leading newlines are acceptable for an input to be considered valid HTML.

**Comment by j256** [comment]
This has been fixed in version 1.9.  I added a unit test for it as well.  Thanks @Abdull .

**Comment by j256** [comment]
See: https://github.com/j256/simplemagic/pull/16

**Comment by Abdull** [comment]
Thank you for your commitment to *SimpleMagic*!

I gave version `1.9` a try.

Using my `testContentInfoUtil @Test` from above threw a `NullPointerException` for version `1.8`, as `anotherHtmlContentInfo` was `null`.

The test also fails in version `1.9`.  It's no longer a `NullPointerException`. But `anotherHtmlContentType` is `ContentType.OTHER`, not the expected `ContentType.HTML`.

**Comment by j256** [comment]
Sorry @Abdull, I don't quite understand your post.  Are you saying that tests are failing?  They are working for me and the release process tests then as well.  Can you post the errors and then open a _new_ issue around that?

**Comment by Abdull** [comment]
On my machine, with version `1.9`, the following fails:

    String anotherHtml = "\n<!doctype html><title>.</title>"; // notice the leading newline
    ContentInfo anotherHtmlContentInfo = ciu.findMatch( anotherHtml.getBytes(StandardCharsets.UTF_8) );
    ContentType anotherHtmlContentType = anotherHtmlContentInfo.getContentType();
    assertTrue( ContentType.HTML.equals(anotherHtmlContentType) );

`anotherHtmlContentType` is reported of being of type `ContentType.OTHER`.

**Comment by j256** [comment]
Btw @Abdull, this now passes for me in 1.10.  Thanks much.   See: https://github.com/j256/simplemagic/commit/16787b741adac57941e7944be24fa008fb7ec065
