### ISSUE TITLE
Support for detecting Illustrator files

### ISSUE THREAD

**Issue by markwoon** [j256/simplemagic#20]
Would it be possible to add support for Illustrator files?

This seems to show that it's possible: https://asecuritysite.com/forensics/magic

**Comment by j256** [comment]
Can you post a sample file somewhere that I can test against?

**Comment by markwoon** [comment]
Attached: [test.zip](https://github.com/j256/simplemagic/files/704249/test.zip)

**Comment by j256** [comment]
Right now the .ai files seem to be showing up as PDF files.  My linux file and osx file commands agree.  Is that not what's happening with your files?

**Comment by j256** [comment]
Ok.  I added some patterns that may detect some portion of the AI files.  See https://github.com/j256/simplemagic/commit/e945b4cc0e8faa430d1b66b47ba9c291a1e814e7

**Comment by markwoon** [comment]
FYI, this has been working well for me.  Thanks.

**Comment by j256** [comment]
Glad to hear it @markwoon .  Thanks for letting me know.
