### ISSUE TITLE
mimeType = null for some mpg files

### ISSUE THREAD

**Issue by air-hermes** [j256/simplemagic#22]
The attached file has mimetype='video/mpeg' but the simplemagic got null

[trn_over_under_adj_2000.zip](https://github.com/j256/simplemagic/files/714183/trn_over_under_adj_2000.zip)

**Comment by j256** [comment]
Fixed.  Thanks.  https://github.com/j256/simplemagic/commit/bf9392ff41c9a5da484f4a7055cac695069f48f0
