### ISSUE TITLE
webm being incorrectly read as application/octet-stream

### ISSUE THREAD

**Issue by t6nand** [j256/simplemagic#23]
Hi, 
Seems like simplemagic fails detecting webm files and returns with ContentType OTHER as it's mimetype being read is "application/octet-stream" instead of "video/webm".

Sample webm file for which it failed: 
http://techslides.com/demos/sample-videos/small.webm

**Comment by j256** [comment]
Thanks.  I'll take a look.

**Comment by Solido** [comment]
Oh yeah this one is really important ! Thx @j256

**Comment by j256** [comment]
Just fixed.  Thanks again.

**Comment by t6nand** [comment]
Thanks @j256
