### ISSUE TITLE
MagicEntry parser doesn't handle octal and hex the same way as the "file" command.

### ISSUE THREAD

**Issue by crawley** [j256/simplemagic#32]
The "man 5 magic" manual entry is unclear (to say the least) about how escapes are treated.  However, if you look at the source-code for the "file" command, the treatment is as folllows:

  - an octal escape is "\" followed by 1, 2 or 3 octal digits, and
  - a hex escape is a "\" followed by 1 or 2 hex digits.

That's not what simplemagic does.  It actually expects exactly 3 octal digits (or "\0" as a special case) and exactly 2 hex digits.

(This was determined by printing MagicEntry objects, and confirmed by source code examination.)

**Comment by crawley** [comment]
#34 is a fix for this

**Comment by crawley** [comment]
Make that #37 ....

**Comment by j256** [comment]
Thanks much for this.  I fixed this a different way.  See: https://github.com/j256/simplemagic/commit/ac9b4fde805cf63003ca46f5d8f6016c852fcdb8
