### ISSUE TITLE
ArrayIndexOutOfBoundsException in com.j256.simplemagic.types.StringType.charFromByte

### ISSUE THREAD

**Issue by charles-jacobsen** [j256/simplemagic#37]
Stack trace:

        java.lang.ArrayIndexOutOfBoundsException: -556514324

	at com.j256.simplemagic.types.StringType.charFromByte(StringType.java:184)
	at com.j256.simplemagic.types.StringType.findOffsetMatch(StringType.java:124)
	at com.j256.simplemagic.types.StringType.isMatch(StringType.java:88)
	at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:146)
	at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:181)
	at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:181)
	at com.j256.simplemagic.entries.MagicEntry.matchBytes(MagicEntry.java:66)
	at com.j256.simplemagic.entries.MagicEntries.findMatch(MagicEntries.java:128)
	at com.j256.simplemagic.entries.MagicEntries.findMatch(MagicEntries.java:122)
	at com.j256.simplemagic.ContentInfoUtil.findMatch(ContentInfoUtil.java:258)

Minimal example:

```
public void test() {
      byte[] x = {
                77,
                90,
                -19,
                -22,
                26,
                -86,
                -36,
                125,
                81,
                56,
                92,
                49,
                -27,
                85,
                125,
                34,
                88,
                -103,
                -55,
                58,
                -21,
                23,
                8,
                48,
                -11,
                121,
                85,
                -26,
                -30,
                45,
                3,
                39,
                -122,
                -68,
                87,
                -26,
                23,
                -15,
                -117,
                104,
                76,
                -100,
                -51,
                36,
                -100,
                29,
                42,
                -69,
                -8,
                56,
                -51,
                -85,
                6,
                -36,
                -118,
                -101,
                -86,
                -68,
                -22,
                -98,
                -20,
                67,
                -44,
                -34,
                -62,
                37,
                -38,
                -12,
                -30
        };

        ContentInfoUtil detector = new ContentInfoUtil();

        detector.findMatch(x);

}
```

I think the issue is in `MagicEntry.OffsetInfo.getOffset`. When `val` is casted to an integer, the result is a negative value. This value ends up being used as an offset into an array.

**Comment by j256** [comment]
Pretty sure this is a dup of https://github.com/j256/simplemagic/issues/30
Thanks.

**Comment by j256** [comment]
Not that I actually look at it, no.  This is a similar but different issue.
