### ISSUE TITLE
findMatch() reads too much bytes

### ISSUE THREAD

**Issue by stokito** [j256/simplemagic#60]
Here is a source of the com.j256.simplemagic.ContentInfoUtil#findMatch(java.io.File) method:

```java
	/**
	 * Number of bytes that the utility class by default reads to determine the content type information.
	 */
	public final static int DEFAULT_READ_SIZE = 10 * 1024;
	private int fileReadSize = DEFAULT_READ_SIZE;

	public ContentInfo findMatch(File file) throws IOException {
		int readSize = fileReadSize;
		if (file.length() < readSize) {
			readSize = (int) file.length();
		}
		if (readSize == 0) {
			return ContentInfo.EMPTY_INFO;
		}
		byte[] bytes = new byte[readSize];
		FileInputStream fis = null;
		try {
			fis = new FileInputStream(file);
			fis.read(bytes);
		} finally {
			closeQuietly(fis);
		}
		return findMatch(bytes);
	}
```

So things unclear for me:
1. Why DEFAULT_READ_SIZE is so big? 10 kibibytes looks too much if most files have only few magic bytes.
2. Derived from the first question: What is a reason to change the fileReadSize?

BTW Result of `fis.read()` is ignored, not sure if this safe.

**Comment by j256** [comment]
1. I think the answer is the "most files".  Some need more bytes and I figured that 10k was pretty small IO wise these days.
2. When you are worried about it reading 10k.  :-)
3. I've added code to pay attention to fis.read() return.  Thanks.

**Comment by stokito** [comment]
ok, then maybe we can make some kind of stream processing and if few bytes was enough then terminate the process.
Also, I'm not sure, but I guess that the size should be rounded to file system page size i.e. 4K
https://en.wikipedia.org/wiki/Page_(computer_memory)

**Comment by j256** [comment]
You linked to a memory page but we are talking about IO.  Most disk subsystems have page sizes a lot less than 4k – it depends highly on the underlying filesystem and IO layers.  512 bytes is often cited.   I don't think it makes that much difference but I'll consider changing it to 8k.

**Comment by j256** [comment]
Oh and streaming would be a big change in the code.  Not a bad idea but non trivial change.
