### ISSUE TITLE
Possible bug inside of MagicEntryParser

### ISSUE THREAD

**Issue by stokito** [j256/simplemagic#61]
com/j256/simplemagic/entries/MagicEntryParser.java:438
```java
			if ("-".equals(offsetOperator)) {
				add = -add;
			} else if ("-".equals(offsetOperator)) {
				offset = add;
				add = 0;
			}
```
Here is duplicated conditions `"-".equals(offsetOperator)`

**Comment by j256** [comment]
Yeah that's not right.  After looking at the code I'm not sure what I was trying to accomplish there but I'm thinking about just removing the else in which case it's not a bug, just ugly and confusing.  Thanks!

**Comment by j256** [comment]
How did you find this @stokito?  Were you trying to fix a bug or just wandering the code?

**Comment by j256** [comment]
Actually no, that's not right.  I understand it now.  That is a bug.  It should be "*" and not "-".  See: https://github.com/j256/simplemagic/commit/ee362ca1b64174dcd7fb57af4d14e77fe0344b51

**Comment by stokito** [comment]
> How did you find this
easily - I tried to figure out how the library works and if it's safe to add to my working project so I decided to checkout sources in IntelliJ and then I just runned `Analayze` and it show a lot of such places.
If you use IntelliJ then you'll see such kind of error just after you made them.
