### ISSUE TITLE
Support for audio/amr

### ISSUE THREAD

**Issue by ledjon** [j256/simplemagic#64]
What would I need to do to add support for "audio/amr" as a file type?

This file type can come from an audio text send from certain android phones (I think this is where it comes from).

You can see it listed here: https://www.twilio.com/docs/sms/accepted-mime-types and the product I work on does get these from time-to-time. 
This type is also listed in /etc/mime.types on my linux system.

I'll gladly make the change/PR but I wanted guidance on what specifically to change besides adding it to the magic file.

Thank you for your time.

**Comment by j256** [comment]
Can you point to a short example file that I can get?

**Comment by ledjon** [comment]
It just so happens that I have one where the user didn't say anything (so there's no privacy data in it):

https://s3.us-east-2.amazonaws.com/aws-codestar-us-east-2-140775790698/recording1475832547.amr

**Comment by j256** [comment]
Got it an added to my test files.  Thanks.  What I see from the command line is "Adaptive Multi-Rate Codec (GSM telephony)".  Is that what you get?   Interestingly I see that in my internal magic file so there is a bug somewheres.  I'm also seeing a mimetype of "audio/amr".  Is that right?

**Comment by ledjon** [comment]
Yes I see the same thing in both cases.  What we do in the app is have an array of mine types that we "allow" and it is based on the enum values of https://github.com/j256/simplemagic/blob/master/src/main/java/com/j256/simplemagic/ContentType.java

So since audio/amr is not in that enum, I don't have a clean way to add it to my array of values to check and I'd rather not add some one-off logic just for this edge case.

**Comment by j256** [comment]
No, I'm wrong.  I just didn't remember how my code worked.  It spits out OTHER but the type is right. 
 Fixed in 5f1247aa60dedf02ebf3a377ee063a0406407968. 

In general, I would suggest that the enum is not enough to handle all cases (obviously) and that you might need to do some sort of inferring of the types.  That said, I'm happy to add missing types as you find them.

**Comment by ledjon** [comment]
Great, thanks!  The enum is just a nice way to reference the critical data types in a list. 

I'll be glad to be able to use the enum now to cover all of the cases we run into.
