### ISSUE TITLE
SVG will be detected as XML

### ISSUE THREAD

**Issue by Tsorki** [j256/simplemagic#7]
The detection of SVG files is not correct. The utility identifies the type as XML, due to the XML header within SVG files. Possible solution is to check what comes after the xml header. There should be an "svg" tag.

**Comment by j256** [comment]
Thanks for this.  I'll look for other patterns around svg.  Do you have a sample file you can attach?

**Comment by Tsorki** [comment]
Of course, there are also tons of SVG in the google image search.
Sorry for the ZIP, but GitHub doesn't allow to uploads SVG's directly:

[signature.zip](https://github.com/j256/simplemagic/files/183625/signature.zip)

**Comment by florinpopescu** [comment]
Same here. 😃

**Comment by j256** [comment]
Ok.  Great example.  I was missing handling of <>= support.  Wow, what a miss.  This has been added to tests and fixed in trunk.

**Comment by Tsorki** [comment]
Did you create a new release for that? We're using maven and need to have a release version for that.
