### ISSUE TITLE
Cannot build from command line using mvn clean verify due to bad javadoc

### ISSUE THREAD

**Issue by robstryker** [j256/simplemagic#9]
Javadoc is pretty bad here.  Can't build from commandline.

**Comment by j256** [comment]
Sorry but I'm not going to fix this.  My javadocs aren't "bad" just that they don't succeed in that checker which IMO sucks.

**Comment by robstryker** [comment]
You could have just merged https://github.com/j256/simplemagic/pull/10/files   ;) 

I admit my javadocs weren't much better, but at least they would have built =P
